### ISSUE TITLE
Merchant's usability

### ISSUE THREAD

**Issue by r000n** [freicoin/foundation#13]
Merchant
- can't add a new category
- has no delete button

**Comment by jtimon** [comment]
Only users in the "trade_mod" group (you're in) can create and edit categories through the admin:

http://foundation.freicoin.org/admin/trade/category/

Only the admins (me and @maaku ) can delete merchants, but moderators can always invalidate them (and they go to the locked merchants list, which is not seen be regular users, only moderators).

When you invite a new merchant to join, you can suggest him a new category or ask for his opinion.
